title: Chirs' Blog.
description: > # this means to ignore newlines until "baseurl:"
  Christian Kojo Bosso's Blog Page
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Christian K. Bosso # add your name
author-img: Prof.jpg # add your photo
about-author: I am a software and machine learning engineer focusing on building intelligent systems (smart systems; the goal of AI). Always hungry to keep learning like machine. # add description
social-twitter: HDpenbosso # add your Twitter handle
social-facebook: boso.christian # add your Facebook handle
social-github: penbosso # add your Github handle
social-linkedin: christian-bosso-hd # add your Linkedin handle
social-email: ckbosso@st.ug.edu.gh # add your Email address
web: ckb.surge.sh
# Disqus
discus-identifier: Chris # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
